### ISSUE TITLE
Be able to use Au home cloud url when create/update/get broker services

### ISSUE THREAD

**Issue by CShen-Bunnings** [solace-iot-team/ansible-solace-collection#31] opened 2022-04-21 00:53 UTC
Hi,

We are using Australia home cloud for our solace cloud services at Bunnings, but the service api url is "api.solacecloud.com.au " instead of the common url "api.solace.cloud", as a result we can't use the ansible collection to manipulate with broker services. Could you please help and let us know how long it will take to make it working? 

Regards,

Chuanhui

**Comment by ricardojosegomezulmke** [comment] 2022-04-29 06:55
duplicate of https://github.com/solace-iot-team/ansible-solace-collection/issues/30#issue-1210367343
closing this one.

**Closed as completed by ricardojosegomezulmke** 2022-04-29 06:55 UTC
